# Generated by Django 5.2.4 on 2025-08-04 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingFacilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='facilitators/logos/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilitatorCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('collection_date', models.DateField()),
                ('source_location', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('waste_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_logs.wastecategory')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='waste_logs.recyclingfacilitator')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('metric_type', models.CharField(choices=[('co2_saved', 'CO2 Emissions Saved'), ('water_saved', 'Water Saved'), ('energy_saved', 'Energy Saved'), ('landfill_reduced', 'Landfill Waste Reduced'), ('trees_saved', 'Trees Saved'), ('other', 'Other')], max_length=20)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_metrics', to='waste_logs.recyclingfacilitator')),
            ],
        ),
        migrations.CreateModel(
            name='RecyclingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps', models.TextField(help_text='Detailed steps of the recycling process')),
                ('output_products', models.TextField(blank=True, help_text='Products created from this recycling process', null=True)),
                ('environmental_impact', models.TextField(blank=True, help_text='Environmental benefits of this process', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilitators/processes/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='waste_logs.recyclingfacilitator')),
                ('waste_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_logs.wastecategory')),
            ],
            options={
                'verbose_name_plural': 'Recycling Processes',
            },
        ),
    ]
