# Generated by Django 5.2.3 on 2025-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('plastic', 'Plastic'), ('organic', 'Organic'), ('e-waste', 'E-Waste'), ('general', 'General Sustainability')], max_length=50)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
