# Generated by Django 5.2.4 on 2025-07-15 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_tips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='tip',
            name='audience',
            field=models.CharField(default='Community members', help_text='Target audience for this tip', max_length=100),
        ),
        migrations.AddField(
            model_name='tip',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image to illustrate this tip', null=True, upload_to='recycle_tips/images/'),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_best_practice',
            field=models.BooleanField(default=False, help_text='Is this tip a best practice?'),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_tutorial',
            field=models.BooleanField(default=False, help_text='Is this tip a tutorial?'),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_visual_guide',
            field=models.BooleanField(default=False, help_text='Is this tip a visual guide?'),
        ),
        migrations.AddField(
            model_name='tip',
            name='tutorial_steps',
            field=models.JSONField(blank=True, help_text='JSON data for tutorial steps', null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='category',
            field=models.CharField(choices=[('recyclables', 'Recyclables'), ('compostables', 'Compostables'), ('general_waste', 'General Waste'), ('plastic', 'Plastic'), ('organic', 'Organic'), ('e-waste', 'E-Waste'), ('general', 'General Sustainability')], max_length=50),
        ),
    ]
